---
servers:
  - name: host1
    adapters:
      - endpoint_ports: [ Ethernet3, Ethernet4 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ leaf1, leaf2 ]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host1
          mode: active
  - name: host2
    adapters:
      - endpoint_ports: [ Ethernet3, Ethernet4 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ leaf1, leaf2 ]
        vlans: 20
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host2
          mode: active
  - name: host3
    adapters:
      - endpoint_ports: [ Ethernet3, Ethernet4 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ leaf3, leaf4 ]
        vlans: 30
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host3
          mode: active
  - name: host4
    adapters:
      - endpoint_ports: [ Ethernet3, Ethernet4 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ leaf3, leaf4 ]
        vlans: 40
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel host4
          mode: active
  - name: Internet-fwl
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ borderleaf1, borderleaf2 ]
        vlans: 50
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel Internet-fwl
          mode: active
  - name: Internal-fwl
    adapters:
      - endpoint_ports: [ Ethernet1, Ethernet2 ]
        switch_ports: [ Ethernet8, Ethernet8 ]
        switches: [ borderleaf1, borderleaf2 ]
        vlans: 60
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel Internal-fwl
          mode: active